### ISSUE TITLE
Statusline is Not Hidden When in TrueZen

### ISSUE THREAD

**Issue by FOSSilizedDaemon** [Pocco81/TrueZen.nvim#55] opened 2021-08-13 15:06 UTC
For some reason truezen is not hiding laststatus when I enter it, but rather moving it to the [top of the buffer](https://imgur.com/0BgmIPr.png). I have checked my configuration, but can't seem to find any issues and when I use the default configuration I get the same issue.

My configuration is as follows
```
---------------
--- TrueZen ---
---------------
-- Variable declarations.
local true_zen = require 'true-zen'

true_zen.setup({
	ui = {
		bottom = {
			-- Do not show the status line in the last window.
			laststatus = 0,

			-- Do not show the line and culmn number of the cursor position.
			ruler = false,

			-- Do not show the current mode.
			showmode = false,

			-- Do not show partial command in the last line of the screen.
			showcmd = false,

			-- Use one screen line for the command-line.
			cmdheight = 1,
		},

		top = {
			-- Do not display the line with the tab page labels.
			showtabline = 0,
		},

		left = {
			-- Do not display line numbers.
			number = false,

			-- Do not display relative line numbers.
			relativenumber = false,

			-- Do not draw the signcolumn.
			signcolumn = 'no',
		},
	},

	modes = {
		ataraxis = {
			-- Padding for the left side of the screen.
			left_padding = 32,

			-- Padding for the right side of the screen.
			right_padding = 32,

			-- Padding for the top of the screen.
			top_padding = 1,

			-- Padding for the bottom of the screen.
			bottom_padding = 1,

			-- Ideal writing width area.
			ideal_writing_area_width = {0},

			-- Handle right and left padding for me.
			just_do_it_for_me = true,

			-- Keep the default fold fillchars.
			keep_default_fold_fillchars = true,

			-- Do not use a custome background.
			custome_bg = false,

			-- Close the current buffer on ':q'.
			quit = 'close',

			-- Allow TrueZen to interact with the background.
			bg_configuration = true,

			-- Highlight groups that TrueZen can affect.
			affected_higroups = { NonText = {}, FoldColumn = {}, VertSplit = {}, StatusLine = {},
                                  StatusLineNC = {}, SignColumn = {} }
		},

		focus = {
			-- Margin of error.
			margin_of_error = 5,

			-- Focus method.
			focus_method = 'experimental'
		},
	},

	integrations = {
		-- Enable integration for tmux.
		tmux = true,

		-- Enable integration for bufferline.
		nvim_bufferline = true,

		-- Enable integration for twilight.
		twilight = true,

		-- Disable integration for gitgutter.
		vim_gitgutter = false,

		-- Disable integration for galaxyline.
		galaxyline = false,

		-- Disable integration for gitsigns.
		gitsigns = false,

		-- Disable integration for limelight.
		limelight = false,

		-- Disable integration for airline.
		vim_airline = false,

		-- Disable integration for powerline.
		vim_powerline = false,

		-- Disable integration for signify.
		vim_signify = false,

		-- Disable integration for express_line.
		express_line = false,

		-- Do not integrate witg lualine.
		lualine = false,
	},

	misc = {
		-- Enable on/off commands.
		on_off_commands = true,

		-- Disable ui elements commands.
		ui_elements_commands = false,

		-- Enable cursor by mode.
		cursor_by_mode = true,
	}
})
```

**Comment by Pocco81** [comment] 2021-08-13 16:55
If I remember well, in the README it says that you **should** use a statusline with an integration if possible, otherwise TrueZen will try to hide your statuslines, if it fails, well... It did its best :)

Which statusline plug-in are you using? (If you are using Lualine then read #38)

**Comment by FOSSilizedDaemon** [comment] 2021-08-13 17:54
@Pocco81 I am using [one I wrote](https://gitlab.com/FOSSilized_Daemon/dotfiles/-/blob/master/src/home/.config/nvim/lua/modules/ui/statusline.lua) and am setting it to [statusline](https://gitlab.com/FOSSilized_Daemon/dotfiles/-/blob/master/src/home/.config/nvim/lua/ui.lua#L28).

**Comment by Pocco81** [comment] 2021-08-13 18:00
Could you try Galaxyline.nvim (or any other statusline) to make sure the problem is unrelated to your custom statusline?

**Comment by FOSSilizedDaemon** [comment] 2021-08-13 18:48
@Pocco81 I am getting the same issue. Additionally, going into a file without truezen enabled and running `set laststatus=0` works, but when I am in truezen that does not work.

**Comment by FOSSilizedDaemon** [comment] 2021-08-13 18:53
@Pocco81 

Here are the screenshots. Also note that TrueZen moves my statusline to the top of the buffer instead of keeping it at the bottom. It also seems to create some hidden buffer or something as I am able to move between the current buffer (only one I opened) and some buffer above and below (not one I opened and not shown in `:buffers:`).

- [set laststatus=0 working in random file without truezen](https://imgur.com/a/iSHwyVW)
- [set laststatus=0 not working in truezen (plus statusline being moved to the top)](https://imgur.com/a/8WUbxki)

**Comment by Pocco81** [comment] 2021-08-13 19:09
Which branch are you using?

**Comment by Pocco81** [comment] 2021-08-13 19:14
Also, where is the screenshot with a statusline supported by TrueZen with the integration emble. Just grab galaxyline.nvim, set it up and enable the integration.

We first gotta make sure it's a TrueZen problem and not a problem with your statusline.

**Comment by FOSSilizedDaemon** [comment] 2021-08-13 19:17
> Which branch are you using?

Main.

**Comment by FOSSilizedDaemon** [comment] 2021-08-13 19:18
> Also, where is the screenshot with a statusline supported by TrueZen with the integration emble. Just grab galaxyline.nvim, set it up and enable the integration.
> 
> We first gotta make sure it's a TrueZen problem and not a problem with your statusline.

I can grab it and do that, but I only have this issue with truezen not in any other file and it never happens unless truezen is enabled. But give me a few to get that screenshot real quick.

**Comment by Pocco81** [comment] 2021-08-13 19:53
> not in any other file

What do you mean?

> Main

Are you using the latest commit? Also, since when is this happening? I checked other issues of yours related to TrueZen and it seems like everything was working before.

Since when is this happening? Did you do something specific before it occurred? Or did you update the plugin and the statusline got bored after that?

**Comment by Pocco81** [comment] 2021-08-13 19:55
> I use the default configuration I get the same issue.

Are you sure about that? Btw update your config. It's a little bit outdated. I've changed some stuff, most importantly the names of the settings.

**Comment by FOSSilizedDaemon** [comment] 2021-08-14 16:12
> > not in any other file
> 
> What do you mean?
> 
> > Main
> 
> Are you using the latest commit? Also, since when is this happening? I checked other issues of yours related to TrueZen and it seems like everything was working before.
> 
> Since when is this happening? Did you do something specific before it occurred? Or did you update the plugin and the statusline got borked after that?

Let me explain with an example just to clear up any misunderstandings.

Lets say I have a text file named `somefile.txt` and open it in neovim, e.g.
```
st
nvim somefile.txt
```
With this file opened in neovim, and **truezen not enabled**, I can the run `set laststatus=0` and my statusline is no longer shown. However, if I have a markdown file named `somefile.md` and open that in neovim **with truezen enabled**, e.g
```
nvim markdown.md
:TZAtaraxis 
```
and then try to disable my statusline
```
set laststatus=0
```
the statusline will not be effected. In otherwords, when I am in a file that does not have TrueZen running I am able to hide and show my statusline whenever I want but if any TrueZen mode is running then I can't.

**Comment by FOSSilizedDaemon** [comment] 2021-08-14 16:14
> > I use the default configuration I get the same issue.
> 
> Are you sure about that? Btw update your config. It's a little bit outdated. I've changed some stuff, most importantly the names of the settings.
> 
> > never happens unless truezen is enabled
> 
> Please try to be more specific, saying that it's "enabled" is very ambiguous. Enabled in the sense that the plugin is loaded? Enabled in the sense that x mode is on?

I will update my configuration today and see if that fixes it (I will refer to config.lua for the changes).

I updated my terminology in my prior response to be more specific.

**Comment by FOSSilizedDaemon** [comment] 2021-08-16 00:09
@Pocco81 I went through the config.lua in master and updated my configuration file to the changes. I am still experiencing this issue with only TrueZen ;-;

**Comment by Pocco81** [comment] 2021-08-17 04:33
Ok so after #56 I ended up improving the system for hiding unsupported statuslines! so technically this issue could be closed. However, regarding:

> With this file opened in neovim, and truezen not enabled, I can the run set laststatus=0 and my statusline is no longer shown. However, if I have a markdown file named somefile.md and open that in neovim with truezen enabled, e.g

Well...

https://user-images.githubusercontent.com/58336662/129662081-6d99d954-44ef-4f81-a5ea-0bced23494dc.mp4

`laststatus` hides the statusline that's at the bottom of nvim (not necessarily like that, but it's a good way of viewing it). Here I opened a split and set it to 0, as you can see the statusline that I was using in the video appeared in the buffer above regardless of `statusline` being set to 0. So don't expect that setting to hied your line inside and outside of truezen [with horizontal splits].

Now, about this:

![image](https://user-images.githubusercontent.com/58336662/129662501-78dcc065-bcc2-46d3-8a08-c8089607b3c5.png)

TrueZen does not open normal buffers, it opens [scratch buffers](https://vi.stackexchange.com/questions/11310/what-is-a-scratch-window); why? because of [the things that can be done with them](https://vimhelp.org/windows.txt.html#special-buffers) The statuslines are the ones in charged of setting their style/shape/etc on the buffer according to certain events and variables. Being having a `scratch` buffer one of them.

In my personal experience I've dealt with several statuslines that suck at this, for example: lightline.vim and lualine.nvim. Proof:

https://user-images.githubusercontent.com/58336662/129663519-361caec5-37f4-4856-bbdd-ddbd32c19acd.mp4

The rest of the ones I've used handle properly these things. Also, don't think that I'm bashing your or any the other statusline creators' work or anything. Showing the `[Scratch]` thing is what nvim does by default actually:

https://user-images.githubusercontent.com/58336662/129663904-f50345bc-149a-414f-88f5-3c1a382314b0.mp4

So, I'd suggest you:
+ consider adding this behaviour to your statusline.
+ consider using TrueZen events for this.

Furthermore, I'd consider adding something to fix this **even though I don't think TrueZen should be the one handling this**.

Btw, change the title of this issue, it's misleading regarding what you replied to my questions above.

**Comment by dm9pZCAq** [comment] 2021-08-17 10:21
# lightline

i found something useful in `goyo` sources:

https://github.com/junegunn/goyo.vim/blob/a865dec7ca7616dbbd69315ad1417b84d0c411f8/autoload/goyo.vim#L226-L230

and now i had in config:
```moon
import g, fn from vim
true_zen = require 'true-zen'


is_lightline = false

if_lightline = (func) ->
	if is_lightline or fn.exists('#lightline') == 1
		is_lightline = true
		func!


true_zen.before_mode_ataraxis_on = ->
	if_lightline ->
		fn['lightline#disable']!

true_zen.after_mode_ataraxis_off = ->
	if_lightline ->
		fn['lightline#enable']!
```

<details><summary>lua</summary>

```lua
local g, fn
do
  local _obj_0 = vim
  g, fn = _obj_0.g, _obj_0.fn
end
local true_zen = require('true-zen')
local is_lightline = false
local if_lightline
if_lightline = function(func)
  if is_lightline or fn.exists('#lightline') == 1 then
    is_lightline = true
    return func()
  end
end
true_zen.before_mode_ataraxis_on = function()
  return if_lightline(function()
    return fn['lightline#disable']()
  end)
end
true_zen.after_mode_ataraxis_off = function()
  return if_lightline(function()
    return fn['lightline#enable']()
  end)
end
```

</details>

**Comment by dm9pZCAq** [comment] 2021-08-17 10:25
and you can see here how it done in `lightline`:

https://github.com/itchyny/lightline.vim/blob/b06d921023cf6536bcbee5754071d122296e8942/autoload/lightline.vim#L45-L80

**Comment by Pocco81** [comment] 2021-08-17 11:44
Thanks @dm9pZCAq! Remember that lightline already has an integration since the issue you opened (#56)

**Comment by Pocco81** [comment] 2021-08-17 11:49
> and you can see here how it done in lightline

Yep, but remember that in the case of @FOSSilizedDaemon he is using a custom statusline, so there is not much to be done from my side.

It's all about events in this case. Yes, I could set events for removing the statusline when leaving a buffer/window, but it won't override the current statusline/user config.

**Comment by Pocco81** [comment] 2021-08-20 18:33
Since OP is gone and a extend explanation was given for the issue, I'm going to close it.

**Closed by Pocco81** 2021-08-20 18:33 UTC
Labels: OP is gone
