### ISSUE TITLE
Refactoring, Code style, Linting, etc.

### ISSUE THREAD

**Issue by YaBoiBurner** [Pocco81/TrueZen.nvim#21] opened 2021-05-07 05:27 UTC
I'm currently (as in editor open right now lol) working on a PR to fix the number of global variables this plugin has, and I noticed that this repo is kinda empty.

Also, a lot of the code looks weird to me (probably mostly because of editor settings).

I'm open to trying to refactor some parts of this plugin for simplicity, but I more importantly would like to ask about formatting & linting.

A code style would be useful for just automating formatting. The ones I'm most familiar with are [StyLua](https://github.com/JohnnyMorganz/StyLua) (Which I recommend for avoiding future arguments over code style), and [LuaFormatter](https://github.com/Koihik/LuaFormatter) (much more configurable than StyLua).
Also, a [`.editorconfig`](https://editorconfig.org/) file would be useful for editor settings.

For linting, there's [selene](https://github.com/Kampfkarren/selene) and [luacheck](https://github.com/mpeterv/luacheck). Both give a lot of errors & warnings right now (although a lot of that is related to globals, which I'm working on a fix for). I *personally* prefer selene.

Some of this stuff could also be integrated into automated checks, such as through github actions or git hooks. But that might be a bit much for now.

---

Is there a set of tools you'd prefer for this? I'm open to setting up anything, but there are already some formatting inconsistencies in the code that this could help with (ex. https://github.com/kdav5758/TrueZen.nvim/blob/main/lua/true-zen/services/bottom/integrations/integration_vim_airline.lua#L12-L16)

**Comment by YaBoiBurner** [comment] 2021-05-07 10:09
Additional note:

StyLua and Selene both fail to parse one file in this repo (`lua/true-zen/services/mode-ataraxis/service.lua`), due to it using the `goto` keyword. But having looked over it, both of them are _relatively_ easy to remove. Not to mention that I'm likely to rewrite _a lot_ of that when I get around to refactoring the codebase.

**Comment by kdav5758** [comment] 2021-05-07 13:30
Hey! Off topic but, weren't you the one that make the other PR for changing the `require()` statements?

> I'm currently (as in editor open right now lol) working on a PR to fix the number of global variables this plugin has, and I noticed that this repo is kinda empty.

Yeah, actually I only learned about what metatables were about 1 week ago but got lazy to implement it in TrueZen.nvim. Thanks for doing this work for me! I'll read the commits in the PR before merging them, tho it seems it's well structured and there is no sketchy code. Thanks.

> Also, a lot of the code looks weird to me (probably mostly because of editor settings).

Not entirely sure why, but the file you put there as an example looks off in GitHub, but good in my Nvim:

My Nvim:
![image](https://user-images.githubusercontent.com/58336662/117452172-11046800-af09-11eb-937b-67e53e929697.png)

GitHub:
![image](https://user-images.githubusercontent.com/58336662/117452210-1cf02a00-af09-11eb-8282-b91a13cd6623.png)


> A code style would be useful for just automating formatting. The ones I'm most familiar with are StyLua (Which I recommend for avoiding future arguments over code style), and LuaFormatter (much more configurable than StyLua).

Sorry but I've never used a code formatter for lua before (actually I'm only one month into Nvim after migrating from Vim) only for Java dev. I'll check them out later and tell which one I like better.

> Also, a .editorconfig file would be useful for editor settings.

I'd like to thank you for mentioning the `.configfile` thing to me! I've been looking for something like this for a while now and I'm really really greatful for you showing me this :+1:

**Comment by ahmedkhalf** [comment] 2021-05-07 15:41
> Not entirely sure why, but the file you put there as an example looks off in GitHub, but good in my Nvim:

Tabs vs spaces, there is probaly some inconsistency between tabs and spaces in the lines shown. On githubs tabs are probably shorther than ur nvim config.

Also off topic, but the init.vim sample config provided in the readme uses tabs which is quite irritating since most init.vim files use spaces so I had to change those.

**Comment by YaBoiBurner** [comment] 2021-05-07 16:27
Yeah, that's a tabs versus spaces issue.

On my config, it looks like this

![](https://user-images.githubusercontent.com/10004812/117479785-5b481200-af26-11eb-9a6f-bf2c56cbd618.png)

I have indents set up as two spaces, and don't really bother with tabs, so it looks more like it does on github

although i've found vim to be so unreliable with how it indents stuff that i just use a formatter where available

also yes the PR for the require fix was from me.

**Comment by kdav5758** [comment] 2021-05-07 17:57
I've been playing around with the `.editorconfig` but there is something that I don't quite get... **my personal** .editorconfig file should be located at `$HOME`, right?, but can I create a custom `.editorconfig` file for one specific directory/one git repo in specific? if so, how would I know which of the two files it's sourcing?

**Comment by YaBoiBurner** [comment] 2021-05-07 18:09
Just place the `.editorconfig` file in the git repo root, and if you want to be safe, add a line saying `root = true` before any other properties.

Although I wouldn't really recommend putting a `.editorconfig` file in your home folder, since that could easily get picked up in other projects.

**Comment by kdav5758** [comment] 2021-05-07 18:17
Not entirely sure if it's working or not but:

https://user-images.githubusercontent.com/58336662/117491748-352a6e00-af36-11eb-9ec6-526b88243eac.mp4


As you can see I have the config file there in the project's root dir + I also installed the [vim extension](https://github.com/editorconfig/editorconfig-vim#readme) that I needed for it to work. It didn't put the final new line as I specified it at the .editorconfig file. I also ran `:EditorConfigEnable` and `:EditorConfigReload` but it doesn't seem to be workin.

Any ideas?

**Comment by YaBoiBurner** [comment] 2021-05-07 18:50
`insert_final_newline` doesn't insert a visible newline. I know that sounds _very_ stupid, but here's a situation where it's actually noticable:

```diff
diff --git a/.prettierrc.toml b/.prettierrc.toml
index 4bbb374..5079898 100644
--- a/.prettierrc.toml
+++ b/.prettierrc.toml
@@ -1 +1 @@
-singleQuote = true
+singleQuote = true
\ No newline at end of file
```

that's just the result of a `git diff`. For a more visual version:

![](https://user-images.githubusercontent.com/10004812/117494557-19c16200-af3a-11eb-80ec-ff9b96ee46a7.png)

`insert_final_newline` inserts a newline character before the end of the file. Hence why those two lines that are very clearly the same are parsed as different things.

Here's what a hex dump of the file looks like without the final newline:

![](https://user-images.githubusercontent.com/10004812/117495057-c6034880-af3a-11eb-9e08-a0c2ed055c85.png)

and the same file with the file with the final newline:

![](https://user-images.githubusercontent.com/10004812/117495186-e8956180-af3a-11eb-9f53-9b19b7d07fc0.png)

It's probably working fine, and you just got unlucky by testing it with a property that has no visual effects.

**Comment by YaBoiBurner** [comment] 2021-05-07 19:07
If you want a quick test to see if editorconfig is working, set `indent_size` to like 37 or 2843 or something

![](https://user-images.githubusercontent.com/10004812/117496441-abca6a00-af3c-11eb-9af8-1faf68862c4f.png)

you'll probably be able to tell _really_ quickly.

![](https://user-images.githubusercontent.com/10004812/117497049-8853ef00-af3d-11eb-972d-dca2c64bf0f1.png)

**Comment by kdav5758** [comment] 2021-05-07 20:59
@YaBoiBurner indeed it's working:
![image](https://user-images.githubusercontent.com/58336662/117507616-e89e5d00-af4c-11eb-9e74-a1e0ed184adf.png)

I'll finish configuring that file then. What other file(s) should the repo have to have better code style/to be more organized...?

**Comment by YaBoiBurner** [comment] 2021-05-07 21:29
I could make a PR to cover some of the more complicated stuff (ex. selene or luacheck config, github actions, etc.)

I'm not all that comfortable deciding the code style, but I could probably add anything else.

**Comment by kdav5758** [comment] 2021-05-08 04:24
Sorry for the late reply. I've been trying to solve some very weird issues caused by the commits in your PR, although I personally **checked** each commit and I still don't see what's wrong:

1. Enabling the tz_ataraxis_focus integration doesn't work as expected when you first enter Atarixis, exit it and then try :TZFocus.
2. The number line appeared when resuming the state of NeoVim while on Ataraxis even if it's specified in the config not to do so.


So I did this:

1. Grabbed the commit before the one that was "causing" the issue. In the case of the second one it was the init.lua file at left/
2. Copy and pasted one from before the PR
3. Tested it and it was working.

In that commit you only added a meta table and put two Funcs and one var in it. Nothing else. I tried doing the same "from scratch" for that file and, for some reason, adding `resume()` to the metatable caused the issue. The same thing was happening with the first issue I mentioned. This doesn't make any sense to me.

As I said, I have no idea why is this happening and yet, I look at your commits and I see nothing wrong in them.

Tomorrow I'll keep trying to "fix it" and if I fail I'll just create a new branch and reset main or something while the issues with the other commits exist.

Any ideas?

**Comment by YaBoiBurner** [comment] 2021-05-09 21:26
I honestly don't really know what broke, but I think it might just be easiest if I try and remove globals as a part of a general refactor.

some of the code here is sorta confusing (`luacheck --max-cyclomatic-complexity 10` says that one function has a complexity of 56) so it's kinda hard to edit some of the code.

**Comment by kdav5758** [comment] 2021-05-10 00:28
> I think it might just be easiest if I try and remove globals as a part of a general refactor.

Thanks! I you are planning on doing a PR afterwards 1. check that stuff is actually working and 2. let me know so that I can check the code too.

> some of the code here is sorta confusing 

In what way?

**Comment by YaBoiBurner** [comment] 2021-05-10 02:30
I'll just use [this](https://github.com/kdav5758/TrueZen.nvim/blob/main/lua/true-zen/services/mode-ataraxis/init.lua#L20-L32) as an example.
```lua
local function toggle()
	if ataraxis_show == 1 then
		ataraxis_false()
	elseif ataraxis_show == 0 then
		ataraxis_true()
	elseif ataraxis_show == nil then
		ataraxis_show = 1
		ataraxis_false()
	else
		ataraxis_show = 1
		ataraxis_false()
	end
end
```
The confusion mostly stems from the usage of numbers in place of booleans, and complex control flows.
A much simpler version might just be:
```lua
local function toggle()
	if ataraxis_show == nil then
		ataraxis_show = true
	end
	return ataraxis_show and ataraxis_false() or ataraxis_true()
end
```
Which I personally find a lot more readable than the original version. (Although that requires refactoring a lot of stuff to work correctly.)

That, and the functions in https://github.com/kdav5758/TrueZen.nvim/blob/main/lua/true-zen/services/mode-ataraxis/service.lua are *very* hard to understand (luacheck says that `load_integrations` has a [cyclomatic complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity) of 56), which can make it hard to tell what exactly it's doing.

**Comment by Pocco81** [comment] 2021-06-03 20:54
**Linting:** Native LSP
**Formatter:** Neoformat + luafmt
**Coding style:** Editorconfig
**Refactored?:** not yet, but I'll be working on that soon.

For now I'm going to close the issue.

**Closed by Pocco81** 2021-06-03 20:54 UTC
